'use client';
import * as React from 'react';
import { ChefHat, Clock3, RefreshCw, Save, ShoppingBasket } from 'lucide-react';
import { api, ApiClientError } from '@/lib/api-client';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { useToast } from '@/components/toast';
import { useT } from '@/i18n/client';

export type Recipe = { mealType: string; title: string; description: string; estimatedCalories: number; macros: { proteinGrams: number; carbohydrateGrams: number; fatGrams: number; fiberGrams: number }; preparationTimeMinutes: number; difficulty: string; ingredients: Array<{ name: string; quantity: number; unit: string; estimatedCalories: number }>; steps: string[]; allergenWarnings: string[]; substitutions: Array<{ original: string; replacement: string; reason: string }> };
type Plan = { remainingTarget: { calories: number; proteinGrams: number; carbohydrateGrams: number; fatGrams: number; fiberGrams: number }; meals: Recipe[]; estimatedDailyTotal: { calories: number; proteinGrams: number; carbohydrateGrams: number; fatGrams: number; fiberGrams: number } };

export function DailyPlanPanel({ date }: { date: string }) {
  const [plan, setPlan] = React.useState<Plan | null>(null); const [loading, setLoading] = React.useState(false); const [saved, setSaved] = React.useState<string[]>([]); const toast = useToast(); const t = useT();
  async function generate(force = false) { setLoading(true); try { const result = await api.post<{ plan: Plan }>('/api/meal-plan', { date, force }); setPlan(result.plan); } catch (error) { toast.push(error instanceof ApiClientError ? error.message : t('recipes.generateFailed'), 'error'); } finally { setLoading(false); } }
  async function saveRecipe(recipe: Recipe) { try { await api.post('/api/recipes', recipe); setSaved((current) => current.includes(recipe.title) ? current : [...current, recipe.title]); toast.push(t('recipes.save'), 'success'); } catch (error) { toast.push(error instanceof ApiClientError ? error.message : t('recipes.generateFailed'), 'error'); } }
  return <section className="space-y-4"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h2 className="flex items-center gap-2 text-xl font-semibold"><ChefHat className="h-5 w-5 text-primary" aria-hidden="true" />{t('recipes.title')}</h2><p className="text-sm text-muted-foreground">{t('recipes.description')}</p></div><Button onClick={() => void generate(Boolean(plan))} loading={loading}><RefreshCw className="h-4 w-4" aria-hidden="true" />{plan ? t('recipes.newSuggestion') : t('recipes.createSuggestions')}</Button></div>
    {plan ? <><Card><CardContent className="grid gap-3 p-4 sm:grid-cols-5">{[[t('recipes.calories'), plan.remainingTarget.calories], [t('recipes.protein'), `${plan.remainingTarget.proteinGrams}g`], [t('recipes.carbs'), `${plan.remainingTarget.carbohydrateGrams}g`], [t('recipes.fat'), `${plan.remainingTarget.fatGrams}g`], [t('recipes.fibre'), `${plan.remainingTarget.fiberGrams}g`]].map(([label, value]) => <div key={String(label)}><p className="text-xs text-muted-foreground">{t('recipes.remaining')} {label}</p><p className="text-lg font-semibold tabular-nums">{value}</p></div>)}</CardContent></Card><div className="grid gap-4 lg:grid-cols-3">{plan.meals.map((recipe) => <RecipeCard key={recipe.mealType} recipe={recipe} saved={saved.includes(recipe.title)} onSave={() => void saveRecipe(recipe)} />)}</div></> : <Card><CardContent className="flex min-h-36 items-center justify-center p-6 text-center text-sm text-muted-foreground">{t('recipes.empty')}</CardContent></Card>}
    <p className="text-xs text-muted-foreground">{t('recipes.disclaimer')}</p></section>;
}

function RecipeCard({ recipe, saved, onSave }: { recipe: Recipe; saved: boolean; onSave: () => void }) { const t = useT(); return <Card className="flex h-full flex-col"><CardHeader><CardDescription>{recipe.mealType === 'BREAKFAST' ? t('recipes.breakfast') : recipe.mealType === 'LUNCH' ? t('recipes.lunch') : t('recipes.dinner')}</CardDescription><CardTitle>{recipe.title}</CardTitle><p className="text-sm text-muted-foreground">{recipe.description}</p></CardHeader><CardContent className="flex flex-1 flex-col gap-3"><div className="flex flex-wrap gap-2 text-sm"><span className="font-semibold">{Math.round(recipe.estimatedCalories)} kcal</span><span className="flex items-center gap-1 text-muted-foreground"><Clock3 className="h-4 w-4" aria-hidden="true" />{recipe.preparationTimeMinutes} min · {recipe.difficulty}</span></div><p className="text-xs text-muted-foreground">P {recipe.macros.proteinGrams}g · C {recipe.macros.carbohydrateGrams}g · F {recipe.macros.fatGrams}g · {t('recipes.fibre')} {recipe.macros.fiberGrams}g</p><details><summary className="cursor-pointer text-sm font-medium">{t('recipes.ingredientsSteps')}</summary><div className="mt-2 space-y-2 text-sm"><ul className="list-disc pl-5">{recipe.ingredients.map((i) => <li key={i.name}>{i.name} · {i.quantity} {i.unit}</li>)}</ul><ol className="list-decimal space-y-1 pl-5">{recipe.steps.map((s, i) => <li key={`${i}-${s}`}>{s}</li>)}</ol></div></details>{recipe.allergenWarnings.length ? <p className="rounded-md border border-amber-500/30 bg-amber-500/10 p-2 text-xs text-amber-800">{t('recipes.allergens')}: {recipe.allergenWarnings.join(', ')}</p> : null}<div className="mt-auto flex gap-2 pt-2"><Button size="sm" variant="outline" onClick={onSave} disabled={saved}><Save className="h-4 w-4" aria-hidden="true" />{t('recipes.save')}</Button><Button size="sm" variant="ghost"><ShoppingBasket className="h-4 w-4" aria-hidden="true" />{t('recipes.shoppingList')}</Button></div></CardContent></Card>; }
