'use client';
import * as React from 'react';
import { BookOpen, Clock3, Trash2 } from 'lucide-react';
import { api, ApiClientError } from '@/lib/api-client';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { useToast } from '@/components/toast';
import { useT } from '@/i18n/client';

type Recipe = { mealType: string; title: string; description: string; estimatedCalories: number; macros: { proteinGrams: number; carbohydrateGrams: number; fatGrams: number; fiberGrams: number }; preparationTimeMinutes: number; difficulty: string; ingredients: Array<{ name: string; quantity: number; unit: string }>; steps: string[]; allergenWarnings: string[] };
type Saved = { id: string; createdAt: string; recipe: Recipe };

export function SavedRecipes() {
  const t = useT(); const toast = useToast(); const [items, setItems] = React.useState<Saved[]>([]); const [loading, setLoading] = React.useState(true);
  React.useEffect(() => { void api.get<{ recipes: Saved[] }>('/api/recipes').then((result) => setItems(result.recipes)).catch(() => toast.push(t('recipes.generateFailed'), 'error')).finally(() => setLoading(false)); }, [t, toast]);
  async function remove(id: string) { try { await api.delete(`/api/recipes/${id}`); setItems((current) => current.filter((item) => item.id !== id)); } catch (error) { toast.push(error instanceof ApiClientError ? error.message : t('recipes.generateFailed'), 'error'); } }
  return <section className="space-y-5"><div><h2 className="flex items-center gap-2 text-xl font-semibold"><BookOpen className="h-5 w-5 text-primary" aria-hidden="true" />{t('recipes.savedTitle')}</h2><p className="text-sm text-muted-foreground">{t('recipes.savedSubtitle')}</p></div>{loading ? <Card><CardContent className="p-6 text-sm text-muted-foreground">{t('common.loading')}</CardContent></Card> : items.length === 0 ? <Card><CardContent className="flex min-h-40 items-center justify-center p-6 text-center text-sm text-muted-foreground">{t('recipes.empty')}</CardContent></Card> : <div className="grid gap-4 lg:grid-cols-2">{items.map(({ id, recipe }) => <Card key={id} className="flex h-full flex-col"><CardHeader><CardDescription>{recipe.mealType === 'BREAKFAST' ? t('recipes.breakfast') : recipe.mealType === 'LUNCH' ? t('recipes.lunch') : t('recipes.dinner')}</CardDescription><CardTitle>{recipe.title}</CardTitle><p className="text-sm text-muted-foreground">{recipe.description}</p></CardHeader><CardContent className="flex flex-1 flex-col gap-3"><div className="flex flex-wrap gap-3 text-sm"><span className="font-semibold">{Math.round(recipe.estimatedCalories)} kcal</span><span className="flex items-center gap-1 text-muted-foreground"><Clock3 className="h-4 w-4" aria-hidden="true" />{recipe.preparationTimeMinutes} min · {recipe.difficulty}</span></div><p className="text-xs text-muted-foreground">P {recipe.macros.proteinGrams}g · C {recipe.macros.carbohydrateGrams}g · F {recipe.macros.fatGrams}g · {t('recipes.fibre')} {recipe.macros.fiberGrams}g</p><details><summary className="cursor-pointer text-sm font-medium">{t('recipes.ingredientsSteps')}</summary><div className="mt-2 space-y-3 text-sm"><ul className="list-disc space-y-1 pl-5">{recipe.ingredients.map((ingredient) => <li key={`${ingredient.name}-${ingredient.quantity}`}>{ingredient.name} · {ingredient.quantity} {ingredient.unit}</li>)}</ul><ol className="list-decimal space-y-1 pl-5">{recipe.steps.map((step, index) => <li key={`${index}-${step}`}>{step}</li>)}</ol></div></details>{recipe.allergenWarnings.length ? <p className="rounded-md border border-amber-500/30 bg-amber-500/10 p-2 text-xs text-amber-800">{t('recipes.allergens')}: {recipe.allergenWarnings.join(', ')}</p> : null}<div className="mt-auto pt-2"><Button size="sm" variant="ghost" onClick={() => void remove(id)}><Trash2 className="h-4 w-4" aria-hidden="true" />{t('common.delete')}</Button></div></CardContent></Card>)}</div>}</section>;
}
